### ISSUE TITLE
zsh history 解析 fix

### ISSUE THREAD

**Issue by soxft** [lihaoyun6/xHistory#1]
macos 15.1
zsh 5.9

fix:
zsh 的 ~/.zsh_history 格式似乎为类似
```
: 1731311342:0;upgrade_oh_my_zsh
: 1731311352:0;omz
: 1731311355:0;omz version
: 1731311357:0;zsh
: 1731311403:0;xhistory
```
<img width="610" alt="image" src="https://github.com/user-attachments/assets/83f755ac-7d24-47fd-8cc7-3a0b423f2827">

开头为时间戳，实际解析时, 我认为应该仅显示后方的实际命令历史，应当去除前方的 时间戳部分

perf:
感觉可以新增一个功能，在命令行中输入 xhistory 后，将光标自动 focus 到 搜索框

**Comment by lihaoyun6** [comment]
关于第二个问题:  
已经弄好了, 在即将发布的 v0.1.1 版本中, 打开面板或菜单栏弹窗时都会默认聚焦到搜索框中

**Comment by lihaoyun6** [comment]
> 格式化匹配这个想法可以的，会方便很多！

是的, 因为很多人的history格式可能千差万别, 如果逐一适配是肯定干不过来的. 倒不如让用户自己写正则来匹配

**Comment by soxft** [comment]
> > 格式化匹配这个想法可以的，会方便很多！
> 
> 是的, 因为很多人的history格式可能千差万别, 如果逐一适配是肯定干不过来的. 倒不如让用户自己写正则来匹配

之前一直用的 zsh 提供的 zsh-autosuggestions 插件， 也会有类似的提示效果，这个工具提供了一个搜索功能，比 suggestion 会好用很多
